# Режим работы бота 
mode: 'real'           # real - торговля на реальные деньги, demo - демо-счёт, test - только сообщения
open_new_orders: True  # Открывать новые позиции или только закрываем уже существующие

# Параметры ордеров
min_order: 42         # Минимальный размер ордера
max_order: 50         # Максимальный размер одного плеча в парной позиции
max_pairs: 5          # Максимальное кол-во открытых позиций
leverage: 2           # Плечо
fee_rate: 0.001       # Процент комиссии биржи

# Параметры входа в позицию
# Способ входа в позицию ('direct' - вход при пересечении уровня thresh_in,
#   'reverse_static' - начинаем отслеживать при достижении thresh_in + dist_in,
#   входим в позицию при откате до thresh_in,
#   'reverse_dynamic' - начинаем отслеживать при достижении thresh_in,
#   входим в позицию при откате от максимума на dist_in)
open_method: 'reverse_static' 
                      
thresh_in:  1.8
thresh_out: 0.25
dist_in:    0.5       # Расстояние от уровня thresh_in, при котором начинаем отслеживать пару
dist_out:   0.0       # 
min_alt_zscore: 1.2   # Минимальный уровень рассчитанного альтернативным способом z_score для входа
width_zone_in: 0.1    # Ширина зоны вхождения в сделку при обратном движении z_score

# Параметры таймфрейма
spr_method: 'lr'      # Способ расчёта спреда ('dist' - разность логарифмов двух активов, 
                      #   'lr' - линейная регрессия)
tf: '1h'              # Таймфрейм
wind: 64              # Размер скользящего окна

# Параметры стоп-лосса
sl_profit_ratio: 0.1  # Выходим из позиции при потере 10% от общего размера позиции
sl_spread_std:   8.0  # Выходим из позиции, когда спред вырастает до 8.0 std


# Параметры бектеста
token_pairs_file: './data/token_pairs.txt'
backtest_spr_method: 'lr'      # Способ расчёта спреда при создании датафреймов для бектеста
start_time: "2025-11-16 16:55" # Время первой записи в тренировочной выборке
valid_time: "2025-11-24 17:00" # Время начала бектеста
end_time  : "2025-12-04 21:00" # Дата окончания бектеста

search_space: 
  # "4h": [14, 18, 24, ]
  "1h": [48, 64, 72, 96]