# Режим работы бота 
mode: 'real'          # real - торговля на реальные деньги, demo - демо-счёт, test - только сообщения
open_new_orders: True # Открывать новые позиции или только закрываем уже существующие

# Параметры ордеров
min_order: 42         # Минимальный размер ордера
max_order: 50         # Максимальный размер одного плеча в парной позиции
max_pairs: 6          # Максимальное кол-во открытых позиций
leverage: 2           # Плечо
fee_rate: 0.00055     # Процент комиссии биржи

# Параметры таймфрейма
spr_method: 'dist'    # Способ расчёта спреда ('dist' - разность логарифмов двух активов, 
                      #   'lr' - линейная регрессия)
tf: '1h'              # Таймфрейм
wind: 96              # Размер скользящего окна
thresh_in: 2.5
thresh_out: 0.25

# Параметры бектеста
token_pairs_file: './bot/config/token_pairs.txt'
backtest_spr_method: 'dist'    # Способ расчёта спреда при создании датафреймов для бектеста
start_time: "2025-11-12 12:00" # Время первой записи в тренировочной выборке
valid_time: "2025-11-19 04:00" # Время начала бектеста
end_time  : "2025-11-24 04:00" # Дата окончания бектеста

search_space: 
  # "4h": [14, 18, 24, ]
  "1h": [48, 64, 72, 96, 120]