# Режим работы бота 
mode: 'real'          # real - торговля на реальные деньги, demo - демо-счёт, test - только сообщения
open_new_orders: True # Открывать новые позиции или только закрываем уже существующие

# Параметры ордеров
min_order: 42         # Минимальный размер ордера
max_order: 50         # Максимальный размер одного плеча в парной позиции
max_pairs: 5          # Максимальное кол-во открытых позиций
leverage: 2           # Плечо
fee_rate: 0.00055     # Процент комиссии биржи

# Параметры таймфрейма
spr_method: 'dist'    # Способ расчёта спреда ('dist' - разность логарифмов двух активов, 
                      #   'lr' - линейная регрессия)
tf: '4h'              # Таймфрейм
wind: 24              # Размер скользящего онка
thresh_in: 2.25
thresh_out: 0.25

# Параметры бектеста
# Файл, содержащий список пар
start_time: "2025-11-09 12:00" # Время первой записи в тренировочной выборке
valid_time: "2025-11-14 12:00" # Время начала бектеста
end_time: "2025-11-18 15:00"   # Дата окончания бектеста

search_space: 
  "4h": [14, 18, 24, 30]
  "1h": [24, 36, 48, 64, 72, 96, 120]