# Режим работы бота 
mode: 'demo'          # real - торговля на реальные деньги, demo - демо-счёт, test - только сообщения
open_new_orders: True # Открывать новые позиции или только закрываем уже существующие

# Параметры ордеров
min_order: 40         # Минимальный размер ордера
max_order: 50         # Максимальный размер одного плеча в парной позиции
max_pairs: 5          # Максимальное кол-во открытых позиций
leverage: 2           # Плечо
fee_rate: 0.00055     # Процент комиссии биржи

# Параметры таймфрейма
tf: '4h'              # Таймфрейм
wind: 24              # Размер скользящего онка
thresh_in: 2.0
thresh_out: 0.5